### ISSUE TITLE
Chat Template For Llama1

### ISSUE THREAD

**Issue by YunzeSong** [chujiezheng/chat_templates#27]
Dear Chujie,

Thank you very much for your contribution to the community. Have you ever made a chat template for LlaMA1? If so, can it be updated? If not, I would also like to express my gratitude. 

Regards,
Yunze

**Comment by chujiezheng** [comment]
Hi, LLaMA-1 does not have official chat/instruction-tuned versions, so there is no chat template for it.

You may simply prompt it with "User/Assistant: ...\n\n", but please take care of the end control of generation (i.e., the generation is ended by the next "Assistant/User:" rather than the eos token).
